# Write your MySQL query statement below
SELECT 
    ROUND(COUNT(DISTINCT B.PLAYER_ID) / COUNT(DISTINCT A.PLAYER_ID), 2) AS fraction
FROM 
    (SELECT PLAYER_ID, MIN(EVENT_DATE) AS EVENT_DATE 
     FROM ACTIVITY 
     GROUP BY PLAYER_ID) A
LEFT JOIN 
    ACTIVITY B 
ON 
    A.PLAYER_ID = B.PLAYER_ID AND B.EVENT_DATE = DATE_ADD(A.EVENT_DATE, INTERVAL 1 DAY);



